### ISSUE TITLE
How is this game  played?

### ISSUE THREAD

**Issue by Dagye95** [MoltenMan/Smog#3]
I tried to play the game but it doesn't seem to work and the window java window leaves the top of the screen.

**Comment by Dagye95** [comment]
I have some code here that will help regulate the frame to the middle of the screen and also add the exit button that is located at the top left of a window

JFrame frame = new JFrame (title); //creating a j frame from the JRE library using with frame as the variable 
		
		frame.setPreferredSize(new Dimension(width, height)); 
		frame.setMaximumSize(new Dimension(width, height)); //setting the size of the window, preferred, maximum and minimum
		frame.setMinimumSize(new Dimension(width, height));
		
		frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE); //lets the user exit the game
		frame.setResizable(false); //doesnt allow resizing of the screen
		frame.setLocationRelativeTo(null); //just lets the user adjust the screen to the middle
		frame.add(game); //adds the game class to the frame
		frame.setVisible(true); // allows me to see the game

**Comment by MoltenMan** [comment]
it isn't nearly finished yet :) this is kinda of a game im making by myself, but if you want you can help.
when it's finished im going to make it so you can program the game itself and such, but it isn't finished AT ALL!!! :)

**Comment by Dagye95** [comment]
Hope the Jframe code can help, what else can I help with?

**Comment by MoltenMan** [comment]
Well i guess you could just make it and do pull requests, i wasn't exactly planning on this being a joint project so i dunno. Also are you sure it leaves the top of the screen? it works for me (if doing nothing is "working" :)
